package net.ntworld.intellijCodeCleaner

const val TOOL_WINDOW_NAME = "Code Cleaner"

const val PROJECT_INITIALIZED = "PROJECT_INITIALIZED"

const val TOGGLE_ANNOTATION = "TOGGLE_ANNOTATION"

const val REQUEST_ANALYZE = "REQUEST_ANALYZE"
const val REQUEST_ANALYZE_SUCCESS = "REQUEST_ANALYZE_SUCCESS"

const val REQUEST_STOP_ANALYZE = "REQUEST_STOP_ANALYZE"
const val REQUEST_STOP_ANALYZE_SUCCESS = "REQUEST_STOP_ANALYZE_SUCCESS"

const val CODE_ANALYZED = "CODE_ANALYZED"
const val RESULT_PARSED = "RESULT_PARSED"
const val CODE_COUNTED = "CODE_COUNTED"

const val REQUEST_COUNTING = "REQUEST_COUNTING"
