package net.ntworld.codeCleaner

import net.ntworld.foundation.EventBus
import net.ntworld.foundation.InfrastructureProvider

// TODO: hacky way, will be fixed with foundation v0.6
class CoreInfrastructure(private val eventBus: EventBus) : InfrastructureProvider() {
    private val included = listOf(
        AutoGeneratedInfrastructureProvider(this)
    )

    init {
        wire(this.root, this.included)
    }

    override fun eventBus(): EventBus = eventBus
}